### ISSUE TITLE
 (EXIT) no process while trying to migrate

### ISSUE THREAD

**Issue by mspanc** [elixir-lang/ecto#747] opened 2015-07-05 14:56 UTC
At some point ecto started to refuse migrations. Other operations (tried ecto.create/ecto.drop) work fine.

I am unable to trigger what change in my code has caused this behaviour, but the stack trace does not help a lot.  

PostgreSQL is running, postgrex is in the application list.

Ecto 0.12.1.

```
** (exit) exited in: GenServer.call(nil, {:query, "SELECT count(1) FROM pg_class c\n  JOIN pg_namespace n ON n.oid = c.relnamespace\n WHERE c.relkind IN ('r','v','m')\n       AND c.relname = 'schema_migrations'\n       AND n.nspname = ANY (current_schemas(false))\n", []}, :infinity)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    (postgrex) lib/postgrex/connection.ex:87: Postgrex.Connection.query/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:37: Ecto.Adapters.Postgres.Connection.query/4
    (stdlib) timer.erl:194: :timer.tc/3
    (ecto) lib/ecto/adapters/sql.ex:191: anonymous fn/6 in Ecto.Adapters.SQL.pool_query!/5
    (ecto) lib/ecto/adapters/sql.ex:615: Ecto.Adapters.SQL.pool_transaction/4
    (ecto) lib/ecto/adapters/sql.ex:189: Ecto.Adapters.SQL.pool_query!/5
    (ecto) lib/ecto/adapters/postgres.ex:59: Ecto.Adapters.Postgres.ddl_exists?/3
```

**Comment by josevalim** [comment] 2015-07-05 16:40
Can you please try master and let us know if the problem is fixed?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment] 2015-07-07 18:38
Ping. Is there any way to reproduce this? Is it fixed in master?

**Comment by mspanc** [comment] 2015-07-07 19:18
I won't be able to check this soon.
7 lip 2015 8:38 PM "José Valim" <notifications@github.com> napisał(a):

**Comment by josevalim** [comment] 2015-07-12 15:56
Please let us know when you have more info to reproduce this and we will gladly reopen!

**Closed by josevalim** 2015-07-12 15:56 UTC
