### ISSUE TITLE
Error using datetime_add and field/2.

### ISSUE THREAD

**Issue by TrevorS** [elixir-lang/ecto#837] opened 2015-07-24 18:38 UTC
Elixir: **1.0.5**
Ecto: **HEAD**

Using a combination of `datetime_add` and `field` to create a query:

```elixir
defp ago(query \\ __MODULE__, field, number, unit) do
  from(q in query, where: field(q, ^field) > datetime_add(^Ecto.DateTime.utc, ^-number, ^to_string(unit)))
end

# ** (ArgumentError) argument error
#     :erlang.apply(0, :type, [])
#     lib/ecto/type.ex:230: Ecto.Type.match?/2
#     lib/ecto/query/builder.ex:263: Ecto.Query.Builder.assert_type!/3
#     lib/ecto/query/builder.ex:90: Ecto.Query.Builder.escape/5
#     lib/ecto/query/builder.ex:142: Ecto.Query.Builder.escape/5
#     lib/ecto/query/builder/filter.ex:16: Ecto.Query.Builder.Filter.build/5
#     expanding macro: Ecto.Query.where/3
#     web/models/batch.ex:2: TsfPix.Batch.ago/4
```

**Comment by josevalim** [comment] 2015-07-24 18:51
I cannot reproduce this. Can you show the ecto entry in your mix.lock? I am thinking maybe you aren't on latest. Maybe do `mix deps.update ecto`, followed by `mix deps.clean ecto` and try again?

**Comment by TrevorS** [comment] 2015-07-24 19:04
`mix.lock` after doing `mix deps.clean ecto` and `mix deps.get ecto`:
```elixir
%{"cors_plug": {:hex, :cors_plug, "0.1.3"},
  "cowboy": {:hex, :cowboy, "1.0.2"},
  "cowlib": {:hex, :cowlib, "1.0.1"},
  "decimal": {:hex, :decimal, "1.1.0"},
  "ecto": {:git, "git://github.com/elixir-lang/ecto.git", "1fc57c3b61b38985d78ae459170f25d1628dd95f", []},
  "erlcloud": {:hex, :erlcloud, "0.9.2"},
  "fs": {:hex, :fs, "0.9.2"},
  "jsx": {:hex, :jsx, "2.1.1"},
  "lhttpc": {:hex, :lhttpc, "1.3.0"},
  "meck": {:hex, :meck, "0.8.3"},
  "mogrify": {:git, "git://github.com/route/mogrify.git", "d19a29fc3bacadfab0f1407162db757ba9433eeb", []},
  "phoenix": {:hex, :phoenix, "0.14.0"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "0.6.0"},
  "phoenix_html": {:hex, :phoenix_html, "1.2.1"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "0.4.3"},
  "plug": {:hex, :plug, "0.13.0"},
  "poison": {:hex, :poison, "1.4.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.9.1"},
  "ranch": {:hex, :ranch, "1.1.0"},
  "uuid": {:hex, :uuid, "1.0.1"}}
```

Here is the context of that function:
```elixir
defmodule TsfPix.Concerns.EctoHelpers do
  defmacro __using__(_) do
    quote do
      alias TsfPix.Repo

      import Ecto.Query, only: [from: 2]

      def all, do: __MODULE__
      def all!, do: all |> Repo.all

      def find(id), do: __MODULE__
      def find!(id), do: find(id) |> Repo.get(id)

      def first(query \\ __MODULE__) do
        from(q in query, order_by: [asc: q.id]) |> from(limit: 1)
      end
      def first!(query \\ __MODULE__), do: first(query) |> Repo.one

      def last(query \\ __MODULE__) do
        from(q in query, order_by: [desc: q.id]) |> from(limit: 1)
      end
      def last!(query \\ __MODULE__), do: last(query) |> Repo.one

      def count(query \\ __MODULE__) do
        from(q in query, select: count(q.id))
      end
      def count!(query \\ __MODULE__), do: count(query) |> Repo.one

      def inserted_ago(query \\ __MODULE__, number, unit) do
        ago(query, :inserted_at, number, unit)
      end
      def inserted_ago!(query \\ __MODULE__, number, unit), do: inserted_ago(query, number, unit) |> Repo.all

      def updated_ago(query \\ __MODULE__, number, unit) do
        ago(query, :updated_at, number, unit)
      end
      def updated_ago!(query \\ __MODULE__, number, unit), do: updated_ago(query, number, unit) |> Repo.all

      defp ago(query \\ __MODULE__, field, number, unit) do
        from(q in query, where: field(q, ^field) > datetime_add(^Ecto.DateTime.utc, ^-number, ^to_string(unit)))
      end
    end
  end
end
```

Same compilation error:
```
== Compilation error on file web/models/user.ex ==
** (ArgumentError) argument error
    :erlang.apply(0, :type, [])
    lib/ecto/type.ex:230: Ecto.Type.match?/2
    lib/ecto/query/builder.ex:263: Ecto.Query.Builder.assert_type!/3
    lib/ecto/query/builder.ex:90: Ecto.Query.Builder.escape/5
    lib/ecto/query/builder.ex:142: Ecto.Query.Builder.escape/5
    lib/ecto/query/builder/filter.ex:16: Ecto.Query.Builder.Filter.build/5
    expanding macro: Ecto.Query.where/3
    web/models/user.ex:2: TsfPix.User.ago/4
```

**Comment by josevalim** [comment] 2015-07-24 19:19
Fixed in master, thank you!

**Closed by josevalim** 2015-07-24 19:19 UTC

**Comment by TrevorS** [comment] 2015-07-24 19:22
Thanks!
