### ISSUE TITLE
Decimals not saved correctly in Postgres DB

### ISSUE THREAD

**Issue by swerter** [elixir-lang/ecto#547] opened 2015-04-01 11:48 UTC
Hi
I think I found a bug when trying to save a decimal into a postgresql database. 
How to reproduce:
Change in the file integration_test/support/migrations.exs the decimal precision to higher value, eg:

    add :cost, :decimal, precision: 5, scale: 3

The integration tests then fails: `MIX_ENV=pg mix test`
```
  1) test primitive types (Ecto.Integration.TypeTest)
     integration_test/cases/type.exs:10
     match (=) failed
     code: [^decimal] = TestRepo.all(from(p in Post, where: p.cost() == ^decimal, select: p.cost()))
     rhs:  [#Decimal<1.00>]
     stacktrace:
       integration_test/cases/type.exs:34
```

I found this error by trying to save a small number (0.002) to postgres as a decimal. The stored value, however, was always 0.2 instead (only one decimal after the dot).

Thanks for your help.

**Comment by josevalim** [comment] 2015-04-01 12:59
The reason the test fails is because the decimal created by Elixir has only 1 digit after the 0 and the database is returning one with 3 digits (which is what you have specified). After correcting the Elixir decimal to contain 3 digits, everything works fine here.

Therefore, I cannot reproduce the issue you are mentioning. If I write 0.002 with the precision+scale you specified, it also works. Which Ecto and Postgrex versions are you using?

**Comment by swerter** [comment] 2015-04-01 13:13
Thanks for the fast response! I am using both, ecto and phoenix, from git. 

Concerning the error, try now to set in integration_test/cases/type.exs, line 15 to

    decimal  = Decimal.new("0.001")

still with precision 5, scale 3. If I do then a 

    IO.inspect TestRepo.all(Post)

I get for cost: #Decimal<0.100>.

**Comment by swerter** [comment] 2015-04-01 13:14
Sorry, lost last line:
`cost: #Decimal<0.100>`

**Comment by josevalim** [comment] 2015-04-01 13:21
@swerter Ok, I see. This seems to be a postgrex issue. Let's summon @ericmj.

**Comment by laurocaetano** [comment] 2015-04-02 23:12
I can confirm that it is a postgrex issue and it is exactly in [this line.](https://github.com/ericmj/postgrex/blob/master/lib/postgrex/extensions/binary.ex#L153)

The given float in this case is `'001'` and the `float_digit` returned by `encode_numeric_float` is `[100]` (it was supposed to return `[001]`, but even fixing it will return `[1]` which is incorrect).

To return the result in the correct order, the [encode_numeric function](https://github.com/ericmj/postgrex/blob/master/lib/postgrex/extensions/binary.ex#L167) is doing a `Enum.reverse` on a single element array. It can be removed, since it will always return the same value.

**Comment by josevalim** [comment] 2015-04-10 09:52
This is fixed in Postgrex.

**Closed by josevalim** 2015-04-10 09:52 UTC
Labels: Kind:Bug, Level:Advanced

**Comment by swerter** [comment] 2015-04-10 10:13
To all, thanks a lot!
