### ISSUE TITLE
mix ecto.migrate 'time out' error

### ISSUE THREAD

**Issue by xihan** [elixir-lang/ecto#1351] opened 2016-04-03 04:47 UTC
### Environment

* Elixir version: 1.2.3
* Database and version: Postgres 9.3
* Ecto version (mix deps): ecto 1.1.5
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: ubuntu 14.04

### Current behavior
I can reproduce this problem with the 'simple app' in the examples folder of ecto github repo.
-> copy examples/simple into a different folder
-> change deps to point to the ecto hex package and compile

mix ecto.create -> works
mix ecto.drop    -> works
starting up the application with 'iex -S mix',
and directly query using Simple.Repo -> works

However, when I run 'mix ecto migrate', I get this error:

** (exit) exited in: :gen_server.call(#PID<0.149.0>, {:checkout, #Reference<0.0.1.531>, true, :infinity}, 5000)
    ** (EXIT) time out
    (db_connection) lib/db_connection/connection.ex:43: DBConnection.Connection.checkout/2
    (db_connection) lib/db_connection.ex:811: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:717: DBConnection.run/3
    (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:421: DBConnection.query/4
    (postgrex) lib/postgrex.ex:111: Postgrex.query/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:31: Ecto.Adapters.Postgres.Connection.query/4
    (ecto) lib/ecto/adapters/sql.ex:259: Ecto.Adapters.SQL.query/7

### Expected behavior
mix migrate should run the migration script.

**Comment by josevalim** [comment] 2016-04-03 07:26
If you use Ecto 2.0.0-beta. Does `mix ecto.create` and `mix ecto.drop` also work?

**Comment by xihan** [comment] 2016-04-03 18:47
Hmm. At one point I thought it did work. 
I just tried it with 2.0.0-beta.2, and 'mix ecto.create | mix ecto.drop' both give the same time out error.

**Comment by josevalim** [comment] 2016-04-09 11:30
@xihan I cannot reproduce this issue. Can you please provide steps for reproducing it? Maybe a sample application or your database configuration. It seems to be something local to your setup rather than an Ecto bug, thank you!

**Comment by josevalim** [comment] 2016-04-09 11:31
Closing for now but I will gladly reopen once we have more info to reproduce this!

**Comment by rodrigoddalmeida** [comment] 2016-04-11 01:38
@josevalim I would guess he is actually reaching the pool timeout (5000ms). The problem is, from what I could test, even with the Repo configured to have both `timeout` and `pool_timeout` other than the defaults, that `DBConnection.Connection.checkout/2` call is still receiving `:infinity` and `5000` as options. 

It should be the case to track the options from Ecto, to Postgrex and DBConnection, and see if they are getting lost in the middle. Any thoughts?

**Comment by josevalim** [comment] 2016-04-16 11:38
Thanks @rodrigoddalmeida!

I have investigated this further and I couldn't reproduce the issues. The timeout values being passed to DBConnection seem correct. Given I still cannot reproduce this issue, I will close it. But if you spot a possible root cause or if anyone can reproduce it, please let us know as it will help tracking any possible bug down.

**Closed by josevalim** 2016-04-16 11:38 UTC
Labels: Note:Needs more info

**Comment by savroff** [comment] 2016-05-17 08:45
Same thing for me, steps for reproduce:
1. Copy example
2. Change dep to 
`{:ecto, "~> 2.0.0-beta"}`
3. Start `mix ecto.create`

I get this:

```
11:44:10.273 [error] Task #PID<0.126.0> started from #PID<0.47.0> terminating
** (stop) exited in: :gen_server.call(#PID<0.127.0>, {:checkout, #Reference<0.0.6.826>, true, 15000}, 5000)
    ** (EXIT) time out
    (db_connection) lib/db_connection/connection.ex:43: DBConnection.Connection.checkout/2
    (db_connection) lib/db_connection.ex:811: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:717: DBConnection.run/3
    (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:421: DBConnection.query/4
    lib/ecto/adapters/postgres.ex:201: anonymous fn/2 in Ecto.Adapters.Postgres.run_query/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
Function: #Function<0.92727848/0 in Ecto.Adapters.Postgres.run_query/2>
    Args: []
```

**Comment by josevalim** [comment] 2016-05-17 09:18
@savroff do you also get this error in the latest RC?

**Comment by savroff** [comment] 2016-05-18 16:19
@josevalim  With `2.0.0-rc.5` yes.

**Comment by josevalim** [comment] 2016-05-18 16:20
Thanks. 

> 1. Copy example

Which example are you copying? I am thinking that maybe you are not being able to connect to the database?

**Comment by savroff** [comment] 2016-05-18 16:24
Example - it's example application :)
I'm changed the version to `1.1` and I can create DATABASE with the same setup, but I have a problem with migration.
```
19:20:36.452 [error] Postgrex.Protocol (#PID<0.267.0>) failed to connect: ** (Postgrex.Error) tcp connect: timeout
```
The thing is I use the same user and password for my ruby app, connection work perfect.

My PSQL version is:
`psql (PostgreSQL) 9.4.1`

**Comment by josevalim** [comment] 2016-05-18 16:27
Ruby uses a unix socket but Phoenix uses a TCP socket. Are you using hostname as localhost? And can you check if `/etc/hosts` contains a `localhost` definition in there? If not, can you change your hostname to "127.0.0.1"?

**Comment by savroff** [comment] 2016-05-18 16:29
Yes, this was the problem!
Thanks for this 👍

**Comment by savroff** [comment] 2016-05-18 16:30
But I have in `/etc/hosts`
```
127.0.0.1 localhost
```

**Comment by savroff** [comment] 2016-05-18 17:37
@xihan I think this fix your problem too

**Comment by Themodem** [comment] 2017-02-28 07:43
Some more info around this issue.

If I run mysql locally on the machine everything works as expected.
If I run mysql in docker and expose 3306 then the `ecto.create` command works as expected but the `ecto.migrate` command times out.

**Comment by josevalim** [comment] 2017-02-28 09:01
@Themodem does it run any command or it timeout before any command is executed? It is very likely that Ecto is not being able to communicate to the database and that is leading to the error. You need to check MySQL permissions and see if it is actually responding to the given port.

**Comment by speeddragon** [comment] 2017-09-19 16:27
Today this happen to me when running mix ecto.migrate

```
17:15:40.303 [info]  == Migrated in 2.4s
** (exit) exited in: :gen_server.call(#PID<0.392.0>, {:checkout, #Reference<0.0.1.3316>, true, 15000}, 5000)
    ** (EXIT) time out
    (db_connection) lib/db_connection/poolboy.ex:112: DBConnection.Poolboy.checkout/3
```

It was after made all migrations changes successfully.

Ecto 2.1 
PostgreSQL 9.6
