### ISSUE TITLE
Allow assoc/2 to build queries from different models

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ecto#737] opened 2015-07-02 15:57 UTC
Today, if you want to build a query from multiple associations you have to do something like this:

```elixir
from c in assoc(post, :comments), where: c.user_id == user.id
# or
from c in assoc(user, :comments), where: c.post_id == post.id
```

If `assoc/2` allowed you to give multiple models we could do this instead:

```elixir
assoc([post, user], :comments)
```

**Comment by josevalim** [comment] 2015-07-12 18:46
@gjaldon would you like to give this one a try? :)

**Comment by gjaldon** [comment] 2015-07-12 20:00
@josevalim sure would be glad to give this a try! :)

Need a bit of clarification though, @ericmj . Do you mean:

```elixir
from p in Post, join: assoc(p, :comments), join: assoc(p, :user)
```

And then have `assoc/2` work like?

```elixir
from p in Post, join: assoc(p, [:comments, :user])
```

**Comment by josevalim** [comment] 2015-07-12 20:06
I think he meant the `Ecto.Model.assoc/2`. He wants this to work:

    Ecto.Model.assoc([post, user], :comments)

However, I am not sure how this would be possible without supporting UNIONS? Even more now that we want to support where and what not in associations?

@ericmj?

**Comment by ericmj** [comment] 2015-07-13 09:36
Will the new types of association queries be used in `Ecto.Model.assoc/2`? I'm not sure how that would make sense, if we can build the association from `post` and `user` it doesn't matter if the association has a `where`, the association already exists.

`assoc([post, user], :comments)` should just create the query:

```elixir
from c in Comment, where: c.user_id == ^user.id, where: c.post_id == ^post.id
```

**Comment by josevalim** [comment] 2015-07-13 12:09
that's an `and`, it would never match, we need to do an OR:

    from c in Comment, where: (c.user_id == ^user.id) or (c.post_id == ^post.id)

Which means we could solve the problem I mentioned by keeping each condition inside the where:

    from c in Comment, where: (c.user_id == ^user.id AND assoc conditions) or (c.post_id == ^post.id AND assoc conditions)

The issue is with ordering. If they specify different orders, what do we do? maybe we should just raise?

**Comment by ericmj** [comment] 2015-07-13 12:11
It can match, it will get the comments posted by the given user in the given post.

**Comment by josevalim** [comment] 2015-07-13 12:26
Now I see which query you want to be done. I strongly disagree because multiple entries in assoc becomes an OR:

    assoc([post1, post2], :comments)

Will be:

    where: c.id == post1.id or c.id == post2.id

I see no reason why different models should suddenly become an AND. We could find a way to support what you want, but it certainly isn't via `assoc/2`. I am closing this, someone feel free to start a discussion if you have an idea of a good API.

**Closed by josevalim** 2015-07-13 12:26 UTC
Labels: Kind:Enhancement, Note:Discussion
