### ISSUE TITLE
Ecto 0.13 Sandbox breaks Sqlite.Ecto integration tests

### ISSUE THREAD

**Issue by jazzyb** [elixir-lang/ecto#724] opened 2015-06-30 13:00 UTC
Using the ecto 0.13.0 hex release, I get the following test failures:

```
  6) Ecto.Integration.TypeTest: failure on setup_all callback, tests invalidated
     ** (RuntimeError) cannot begin test transaction with pool Ecto.Adapters.Poolboy.
     In order to use test transactions with Ecto SQL, you need to
     configure your repository to use Ecto.Adapters.SQL.Sandbox:

         pool: Ecto.Adapters.SQL.Sandbox


     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:321: Ecto.Adapters.SQL.test_transaction/3
       integration/sqlite/test_helper.exs:44: Ecto.Integration.Case.__ex_unit_setup_all_0/1
       integration/sqlite/test_helper.exs:40: Ecto.Integration.Case.__ex_unit__/2
       deps/ecto/integration_test/cases/type.exs:3: Ecto.Integration.TypeTest.__ex_unit__/2
```

I noticed that this new sandbox code seems to have been added around #721.  I updated my `test_helper.exs` file to use the Sandbox and added the `Process.flag(:trap_exit, true)` line to the end of the file as well.  When I do that, I get only the following error:

```
** (EXIT from #PID<0.48.0>) already started: #PID<0.167.0>
```

How do I get the integration tests to work again?

My branch with the above failure:  https://github.com/jazzyb/sqlite_ecto/tree/sandbox-failures

**Comment by josevalim** [comment] 2015-06-30 13:15
Yes, it is a bug in the sandbox pool, I will fix it. :)

**Comment by josevalim** [comment] 2015-06-30 13:29
Can you try Ecto master? If it works, I will release v0.13.1. :)

**Comment by jazzyb** [comment] 2015-06-30 13:37
Different errors:

```
  7) Ecto.Integration.RepoTest: failure on setup_all callback, tests invalidated
     ** (exit) exited in: GenServer.call(Ecto.Integration.TestRepo.Pool, {:query, :begin, &Ecto.Integration.TestRepo.log/1, [timeout: 5000]}, 5000)
         ** (EXIT) no process
     stacktrace:
       (elixir) lib/gen_server.ex:356: GenServer.call/3
       (ecto) lib/ecto/adapters/sql.ex:335: Ecto.Adapters.SQL.test_transaction/4
       integration/sqlite/test_helper.exs:44: Ecto.Integration.Case.__ex_unit_setup_all_0/1
       integration/sqlite/test_helper.exs:40: Ecto.Integration.Case.__ex_unit__/2
       deps/ecto/integration_test/cases/repo.exs:1: Ecto.Integration.RepoTest.__ex_unit__/2
```

**Comment by josevalim** [comment] 2015-06-30 13:51
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by josevalim** [comment] 2015-06-30 13:51
Please ignore my message, I clicked the wrong button. :D

**Comment by josevalim** [comment] 2015-06-30 13:52
The root cause is this. We are getting `{:error, {:sqlite_error, 'cannot start a transaction within a transaction'}}` as reply and Ecto requires your query to return `{:error, Exception.t}`, so we can raise those errors.

**Comment by josevalim** [comment] 2015-06-30 14:13
Fixed in master. Also, you may want to integrate all of your tests together or set `build_per_environment: false` in your mix.exs so you don't compile everything twice all the time. :)

**Closed by josevalim** 2015-06-30 14:13 UTC

**Comment by jazzyb** [comment] 2015-06-30 14:22
Ah.  Okay.  Thank you.  I'll look into that.

**Comment by jazzyb** [comment] 2015-06-30 14:37
Will there be a 0.13.1 release?

**Comment by josevalim** [comment] 2015-06-30 14:39
Yes, are you ready? :)

**Comment by jazzyb** [comment] 2015-06-30 14:47
Yep :)  I didn't change anything in Sqlite.Ecto, but it's working with master.

**Comment by josevalim** [comment] 2015-06-30 15:37
v0.13.1 is out. :)

**Comment by jazzyb** [comment] 2015-06-30 16:28
Thanks for your help, José!
