### ISSUE TITLE
cannot dump/cast/load :binary_id type

### ISSUE THREAD

**Issue by mobileoverlord** [elixir-lang/ecto#645] opened 2015-06-05 13:58 UTC
Ecto.Type.cast/2 throws the folloring error when trying to cast a binary UUID in a changeset in Ecto 0.12.0-rc
```elixir
** (RuntimeError) cannot dump/cast/load :binary_id type, attempted value: "d965afab-d71e-4616-bd8f-f7604cb3df27"
      (ecto) lib/ecto/type.ex:538: Ecto.Type.of_base_type?/2
      (ecto) lib/ecto/type.ex:502: Ecto.Type.cast/2
      (ecto) lib/ecto/changeset.ex:258: Ecto.Changeset.cast_field/3
      (ecto) lib/ecto/changeset.ex:234: Ecto.Changeset.process_param/6
    (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
      (ecto) lib/ecto/changeset.ex:220: Ecto.Changeset.cast/4
```

**Comment by gjaldon** [comment] 2015-06-08 18:29
I think that's the expected behavior. You cannot dump/cast/load `:binary_id` type like it says in the error msg. Maybe try using `Ecto.UUID` instead?

**Comment by josevalim** [comment] 2015-06-08 19:23
This is a bug in Ecto. We cannot dump/cast/load because it is supposed to be handled before hand. The error message we have today is basically to help us catch bugs.

**Comment by gjaldon** [comment] 2015-06-09 16:48
I see. Where is it supposed to be handled? 

> We cannot dump/cast/load because it is supposed to be handled before hand.
Is this also the behavior expected when `:binary_id` is not autogenerated? Because looking at `Ecto.Type.cast/2` for `:binary_id`, all it does is raise the error above.

**Comment by josevalim** [comment] 2015-06-20 16:23
Part 1 fixed on master. We have decided to treat team as binaries in the changeset and do the dump check when writing to the repository. We are going to introduce Repo.insert! and allow some errors to be added by the repository.

**Closed by josevalim** 2015-06-20 16:23 UTC
