### ISSUE TITLE
Ecto.Changeset.html#validate_length/3 with empty list

### ISSUE THREAD

**Issue by spscream** [elixir-lang/ecto#1306] opened 2016-03-09 14:35 UTC
### Environment

* Elixir version (elixir -v): Elixir 1.2.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5
* Ecto version (mix deps): 1.1.4

### Current behavior
```elixir
defmodule ValidateLengthTest do
  use ExUnit.Case, async: true
  import Ecto.Changeset

  defmodule Group do
    use Ecto.Schema

    schema "groups" do
      field :members, {:array, :integer}
    end
  end

  defp changeset(model \\ %Group{}, params) do
      cast(model, params, ~w(), ~w(members))
  end

  test "validate_length/3 with list" do
    changeset = changeset(%{"members" => []}) |> validate_length(:topics, min: 6, foo: true)

    refute changeset.valid?
    assert changeset.errors == [members: {"should have at least %{count} item(s)", count: 6}]
  end
end
```

this test returns an error:
```elixir
  1) test validate_length/3 with list (ValidateLengthTest)
     test/validate_length_test.exs:17
     Expected false or nil, got true
     code: changeset.valid?()
     stacktrace:
       test/validate_length_test.exs:20



Finished in 0.2 seconds (0.2s on load, 0.00s on tests)
1 test, 1 failure
```

### Expected behavior

It should check for empty list and valid? should return false, but now validate_change doesn't run validation if empty list is passed as a changed parameter.

**Comment by michalmuskala** [comment] 2016-03-09 14:56
Duplicate of https://github.com/elixir-lang/ecto/issues/981

Current fix is to change default value for the array field to `nil`.

**Closed by michalmuskala** 2016-03-09 14:56 UTC
