### ISSUE TITLE
Ecto 2 rc.4 breaks calecto

### ISSUE THREAD

**Issue by princemaple** [elixir-lang/ecto#1412] opened 2016-05-04 05:12 UTC
cc @lau not sure if it's something that needs to be updated in https://github.com/lau/calecto

### Environment

* Elixir version (elixir -v): 1.2.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5
* Ecto version (mix deps): 2.0.0-rc.4

### Current behavior

I got this error after updating to ecto 2 rc4 from ecto 2 rc3
```
** (exit) an exception was raised:
    ** (Ecto.ChangeError) value `#Ecto.DateTime<2016-05-04 05:07:33.776539>` for `App.Group.updated_at` in `insert` does not match type Calecto.DateTimeUTC
        (ecto) lib/ecto/repo/schema.ex:610: Ecto.Repo.Schema.dump_field!/6
        (ecto) lib/ecto/repo/schema.ex:619: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/repo/schema.ex:617: Ecto.Repo.Schema.dump_fields!/5
        (ecto) lib/ecto/repo/schema.ex:567: Ecto.Repo.Schema.dump_changes!/6
        (ecto) lib/ecto/repo/schema.ex:182: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
        (ecto) lib/ecto/repo/schema.ex:595: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
        (db_connection) lib/db_connection.ex:1164: DBConnection.transaction_nested/2
        (db_connection) lib/db_connection.ex:1030: DBConnection.transaction_meter/3
        (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
        (ecto) lib/ecto/multi.ex:374: Ecto.Multi.apply_operation/4
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/adapters/sql.ex:462: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection) lib/db_connection.ex:1079: DBConnection.transaction_run/4
        (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
        (ecto) lib/ecto/repo/queryable.ex:27: Ecto.Repo.Queryable.transaction/4
        (app) web/controllers/api/v1/group_controller.ex:12: App.API.V1.GroupController.create/2
        (app) web/controllers/api/v1/group_controller.ex:1: App.API.V1.GroupController.action/2
        (app) web/controllers/api/v1/group_controller.ex:1: App.API.V1.GroupController.phoenix_controller_pipeline/2
```

### Expected behavior
`inserted_at` and `updated_at` should work as previously did.

**Comment by josevalim** [comment] 2016-05-04 07:19
That's a great catch, thank you @princemaple.

@lau or @princemaple, do you have an easy way to reproduce this issue? If so, I will investigate it straight-away. :)

**Comment by princemaple** [comment] 2016-05-04 07:26
As you can tell, I'm working on a Phoenix app.

Per calecto documentation, I have this in my `web.ex`

```elixir
  def model do
    quote do
      use Ecto.Schema
      use Calecto.Schema, usec: true # notice this

      alias Ecto.Multi
      import Ecto
      import Ecto.Changeset
      import Ecto.Query
    end
  end
```

This should be enough to reproduce the problem, in any phoenix app, for any model that contains timestamps. I got the error as soon as I wanted to create (`Repo.insert`) something.

**Comment by josevalim** [comment] 2016-05-04 08:42
Ok, I know why this is happening.

@lau, the latest RC changed Ecto's autogenerate to return the type (i.e. Ecto.DateTime) instead of a tuple (i.e. `{date, time}`). That's why your datetime implementation is receiving `Ecto.DateTime` in `dump`. We have two options to fix this:

1. We change Ecto to call autogenerate also on your type and you would implement the logic similar to this: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/date_time.ex#L578

2. You change Calecto to be able to dump Ecto.DateTime

My preference is 2 because, even though it is a workaround for now, it will be completely removed once we standardize on the same types.

Furthermore, how do you foresee this working in the future with Elixir 1.3 types? Would the DateTimeUTC become NaiveDateTime?

**Comment by michalmuskala** [comment] 2016-05-04 09:19
I'm for the option 1. For any field that supports `autogenerate` option a similar mechanism is used - the type is expected to expose an `autogenerate/0` function returning the type's value. Why would timestamps be different?

**Comment by josevalim** [comment] 2016-05-04 09:28
@michalmuskala because there are implementation details there (like passing usec) that I don't think we should expose yet. I am also quite sure that all of this won't matter once we depend on Elixir v1.3 calendar types.

**Comment by michalmuskala** [comment] 2016-05-04 09:36
Why would the general case change because of the built-in calendar types? I'm not sure I understand.

I'd rather generalize the solution, than further special case it.

Another option is to always have `autogenerate/1` instead of `autogenerate/0`. In this set-up passing `autogenerate: opts` to a field would call `autogenerate(opts)` on the type.
We could keep `autogenerate: true` calling `autogenerate/0` in order to keep backwards-compatibility.

Do we know of any other use cases for autogenerate besides timestamps? Do we need to worry about that?

**Comment by josevalim** [comment] 2016-05-04 09:51
> I'd rather generalize the solution, than further special case it.

That's exactly what I am trying to avoid. Passing `:usec` or not is an implementation detail to how timestamps work and I don't want to have others relying on it. Both solutions will require special casing.

My plan was to generalize autogenerate so you can pass `{m, f, a}`. I don't think passing `opts` is enough, specially in the future where the default time will likely be `:datetime` or something of sorts. So maybe we should just allow this to be set now.

**Comment by josevalim** [comment] 2016-05-04 09:55
So I have this patch:

```diff
diff --git a/lib/ecto/schema.ex b/lib/ecto/schema.ex
index 78b320f..ac5840a 100644
--- a/lib/ecto/schema.ex
+++ b/lib/ecto/schema.ex
@@ -428,6 +428,8 @@ defmodule Ecto.Schema do
       Microseconds will be 0 if false. Defaults to false.
     * `:inserted_at` - the name of the column for insertion times or `false`
     * `:updated_at` - the name of the column for update times or `false`
+    * `:autogenerate` - a module-function-arity tuple used for generating
+      both insert and update at timestamps
 
   All options can be pre-configured by setting `@timestamps_opts`.
   """
@@ -439,24 +441,22 @@ defmodule Ecto.Schema do
         |> Keyword.merge(@timestamps_opts)
         |> Keyword.merge(opts)
 
-      type = Keyword.fetch!(timestamps, :type)
-      autogen = if Keyword.fetch!(timestamps, :usec), do: [:usec], else: []
+      type    = Keyword.fetch!(timestamps, :type)
+      args    = if Keyword.fetch!(timestamps, :usec), do: [:usec], else: [:sec]
+      autogen = timestamps[:autogenerate] || {Ecto.DateTime, :autogenerate, args}
 
       # TODO: Revisit and expose autogenerate when Elixir's 1.3
       # calendar types are introduced .
 
       if inserted_at = Keyword.fetch!(timestamps, :inserted_at) do
         Ecto.Schema.field(inserted_at, type, [])
-        Module.put_attribute(__MODULE__, :ecto_autogenerate,
-            {inserted_at, {Ecto.DateTime, :autogenerate, autogen}})
+        Module.put_attribute(__MODULE__, :ecto_autogenerate, {inserted_at, autogen})
       end
 
       if updated_at = Keyword.fetch!(timestamps, :updated_at) do
         Ecto.Schema.field(updated_at, type, [])
-        Module.put_attribute(__MODULE__, :ecto_autogenerate,
-            {updated_at, {Ecto.DateTime, :autogenerate, autogen}})
-        Module.put_attribute(__MODULE__, :ecto_autoupdate,
-            {updated_at, {Ecto.DateTime, :autogenerate, autogen}})
+        Module.put_attribute(__MODULE__, :ecto_autogenerate, {updated_at, autogen})
+        Module.put_attribute(__MODULE__, :ecto_autoupdate, {updated_at, autogen})
       end
     end
   end
```

This way calecto will be able to set `:autogenerate` as an option and it will call whatever it wants to.

**Comment by josevalim** [comment] 2016-05-04 14:07
I have merged support for autogenerate because someone has just asked for this feature in the mailing list as well. As long as calecto passes `autogenerate: {m, f, [args]}` to `@timestamp_opts`, we should be golden.

**Closed by josevalim** 2016-05-04 14:07 UTC

**Comment by lau** [comment] 2016-05-04 14:29
Cool, I will implement the `autogenerate` functionality then.

> Furthermore, how do you foresee this working in the future with Elixir 1.3 types? Would the DateTimeUTC become NaiveDateTime?

It would be almost the same as today. The 1.3 types and Calendar types are almost the same. I have copied a table from the readme from Calecto: https://github.com/lau/calecto (under the heading The Types). 

| Primitive type            | Ecto schema type      | Equivalent Calendar type |
| ------------------------- | --------------------- | ------------------------ |
| *Used in migrations*      | *Used in schemas*     | *Type returned from db*  |
| :date                     | Calecto.Date          | Calendar.Date            |
| :time                     | Calecto.Time          | Calendar.Time            |
| :datetime                 | Calecto.DateTimeUTC   | Calendar.DateTime        |
| :datetime                 | Calecto.NaiveDateTime | Calendar.NaiveDateTime   |
| :calendar_datetime        | Calecto.DateTime*     | Calendar.DateTime        |

In a future Calecto version that supports only Elixir 1.3+, the last column would simply lack `Calendar.` from the type names and instead use the Elixir 1.3 types.

Note that there is no `DateTimeUTC` type in Calendar - it is specific to Calecto. 
`Calecto.DateTimeUTC` works with `Calendar.DateTime` structs today.

So why does the `Calecto.DateTimeUTC` exist? Why not just use a `NaiveDateTime`? Because then we lose the valuable information about the timestamps being in UTC. In a DateTime it is explicit. We already know that all the inserted_at and updated_at timestamps are in UTC. Imagine if Logger had `DateTime`s in the future - then you could compare a `DateTime` from Logger to an inserted_at `DateTime` from Ecto to see which happened first. And because the time zone information is preserved you can tell which happened first. Without making assumptions about the timezone.

There are two different Calecto types that can store DateTimes. One is `Calecto.DateTimeUTC` and the other is the currently postgres specific `Calecto.DateTime`.

**Comment by josevalim** [comment] 2016-05-04 14:33
Very helpful, thank you @lau.

**Comment by lau** [comment] 2016-05-07 01:28
@josevalim Thank you for making a solution so quickly. I have pushed a new version of Calecto with this change (https://github.com/lau/calecto/commit/f6bcd248f0f5bf7eb4dd2410524441372c0bed67). Tested it against 2.0.0-rc4 with you patch applied and it worked.

Will your new code come out in a 2.0.0-rc5 version?

**Comment by josevalim** [comment] 2016-05-07 08:38
@lau surely, I will release a -rc5 later today.

**Comment by lau** [comment] 2016-05-09 20:23
OK

**Comment by josevalim** [comment] 2016-05-09 21:51
I forgot to release it. :P I will try to do it tomorrow. :)
