### ISSUE TITLE
Issues when preloading two has_many 'through' same source

### ISSUE THREAD

**Issue by bharrisau** [elixir-lang/ecto#1077] opened 2015-11-10 10:40 UTC
Sorry for the poor quality bug report, I will try to get back and improve it. And this might just be a symptom of #986 anyway.

```
schema "foo" do
  has_many :bars, Bar

  has_many :bazs, through [:bars, :bazs]
  has_many :fizs, through [:bars, :fizs]
end
```

Something like this has issues when trying to preload both `bazs` and `fizs`. It seems to be an `AssociationNotLoaded` on one of the primary_keys. I've worked around it by `Enum.map` the `bars` and calling preload for the two items on each `Bar` which works (probably because there is no `through` involved).

**Comment by josevalim** [comment] 2015-11-10 12:34
Yes, it is a duplicate of #986. :) Thank you for the report!

**Closed by josevalim** 2015-11-10 12:34 UTC
