### ISSUE TITLE
SELECT related JSON map attribute cause error. 

### ISSUE THREAD

**Issue by bartroza** [elixir-lang/ecto#1205] opened 2016-01-16 10:25 UTC
I'm trying to SELECT JSON filed in related model to get eventually `post.tags # => "tags":["narty","wspinaczka"]` by `Post |> Repo.all |> Repo.preload(tags: from(t in Myapp.Tag, select: fragment("?::json->?", t.name, "pl")))`, it seems that ecto want additionally to map `map` field, is it a way to do this only by ecto and sql without Enum.map?

```
post = Repo.get!(Post, id) |> Repo.preload([:tags, :category])
post.tags # => "tags":[{"name":{"pl":"narty","en":"ski"}},{"name":{"pl":"wspinaczka","en":"climbing"}}]

#how preload all with selected key?

posts = Post 
  |> Repo.all 
  |> Repo.preload(tags: from(t in Myapp.Tag, select: fragment("?::json->?", t.name, "pl")))
```

```
** (BadMapError) expected a map, got: "narty"
    (stdlib) :maps.find(:id, "narty")
    (elixir) lib/map.ex:27: Map.fetch!/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:438: :erl_eval.expr/5
       (iex) lib/iex/evaluator.ex:117: IEx.Evaluator.handle_eval/5
```

Migrations:

```
defmodule Myapp.Repo.Migrations.CreateTag do
  use Ecto.Migration

  def change do
    create table(:tags) do
      add :name, :map
      add :category_id, references(:categories)

      timestamps
    end

  end
end

defmodule Myapp.Repo.Migrations.CreateJoinTableTaggings do
  use Ecto.Migration

  def change do
    create table(:taggings) do
      add :post_id, references(:posts)
      add :tag_id, references(:tags)
    end
    create index(:taggings, [:post_id, :tag_id])
  end
end
```

Models:

```
defmodule Myapp.Tag do
  use Myapp.Web, :model

  schema "tags" do
    field :name, :map

    has_many :taggings, Myapp.Tagging
    has_many :posts, through: [:taggings, :post]

    belongs_to :post, Myapp.Post
    timestamps
  end
end

defmodule Myapp.Tagging do
  use Myapp.Web, :model

  schema "taggings" do
    belongs_to :post, Myapp.Post
    belongs_to :tag, Myapp.Tag
  end
end

defmodule Myapp.Post do
  use Myapp.Web, :model

  schema "posts" do
    field :title, :string

    belongs_to :category, Myapp.Category
    has_many :taggings, Myapp.Tagging
    has_many :tags, through: [:taggings, :tag]
    timestamps
  end
end
```

**Comment by josevalim** [comment] 2016-01-16 10:31
This is not supported on Ecto 1.1 but it will be supported on Ecto 2.0 (current master).

**Comment by bartroza** [comment] 2016-02-25 20:58
@josevalim With new Ecto 2.0.beta I got following error:

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Ecto.primary_key!/1
        (ecto) lib/ecto.ex:434: Ecto.primary_key!("narty")
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
```

Custom select is working for string field preload but not for JSON, what am i doing wrong? Preload is still: `Repo.preload(tags: from(t in Myapp.Tag, select: fragment("?::json->?", t.name, "pl")))`

**Comment by josevalim** [comment] 2016-02-25 21:06
Ah, it is a through relationship. I am not sure if this one works, I missed this detail. I will investigate and let you know. :)

**Comment by josevalim** [comment] 2016-02-25 21:08
Yup, I can reproduce the issue. I will work on a fix. :)

**Comment by josevalim** [comment] 2016-02-25 21:16
Fixed in master, please give it a try. We should have a new beta soon.

**Closed** 2016-02-25 21:16 UTC

**Comment by bartroza** [comment] 2016-02-25 21:39
Tested and it is working, thanks a lot!

**Comment by josevalim** [comment] 2016-02-25 22:13
@bartroza unfortunately my commit introduced a bug. Because of how associations work, you will have to choose at least all primary keys alongside your result. I will revert it and make sure to add a decent error message.

**Comment by josevalim** [comment] 2016-02-25 22:13
To be clear, you will need this:

    select: %{id: t.id, data: fragment("?::json->?", t.name, "pl")}
