### ISSUE TITLE
ArgumentError :ets.lookup(217132, 1114)

### ISSUE THREAD

**Issue by johnhamelink** [elixir-lang/ecto#1271] opened 2016-02-22 00:19 UTC
Hey there,

After upgrading to master branch in order to get #1258, I'm now getting the following errors randomly:

```
  1) test Valid JWT (DB.SessionTest)
     test/models/session_test.exs:9
     ** (ArgumentError) argument error
     stacktrace:
       (stdlib) :ets.lookup(217132, 1114)
       (postgrex) lib/postgrex/types.ex:294: Postgrex.Types.fetch!/2
       (postgrex) lib/postgrex/types.ex:215: Postgrex.Types.encoder/2
       (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
       (postgrex) lib/postgrex/query.ex:82: DBConnection.Query.Postgrex.Query.encoders/2
       (postgrex) lib/postgrex/query.ex:43: DBConnection.Query.Postgrex.Query.describe/2
       (db_connection) lib/db_connection.ex:884: DBConnection.describe_execute/5
       (db_connection) lib/db_connection.ex:966: anonymous fn/4 in DBConnection.run_meter/5
       (db_connection) lib/db_connection.ex:421: DBConnection.query/4
       (ecto) lib/ecto/adapters/sql.ex:380: Ecto.Adapters.SQL.struct/6
       (ecto) lib/ecto/repo/schema.ex:369: Ecto.Repo.Schema.apply/5
       (ecto) lib/ecto/repo/schema.ex:175: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:570: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:434: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1079: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
       test/models/session_test.exs:17



  2) test Invalid JWT (DB.SessionTest)
     test/models/session_test.exs:24
     ** (ArgumentError) argument error
     stacktrace:
       (stdlib) :ets.lookup(217132, 1114)
       (postgrex) lib/postgrex/types.ex:294: Postgrex.Types.fetch!/2
       (postgrex) lib/postgrex/types.ex:215: Postgrex.Types.encoder/2
       (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
       (postgrex) lib/postgrex/query.ex:82: DBConnection.Query.Postgrex.Query.encoders/2
       (postgrex) lib/postgrex/query.ex:43: DBConnection.Query.Postgrex.Query.describe/2
       (db_connection) lib/db_connection.ex:884: DBConnection.describe_execute/5
       (db_connection) lib/db_connection.ex:966: anonymous fn/4 in DBConnection.run_meter/5
       (db_connection) lib/db_connection.ex:421: DBConnection.query/4
       (ecto) lib/ecto/adapters/sql.ex:380: Ecto.Adapters.SQL.struct/6
       (ecto) lib/ecto/repo/schema.ex:369: Ecto.Repo.Schema.apply/5
       (ecto) lib/ecto/repo/schema.ex:175: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:570: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:434: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1079: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
       test/models/session_test.exs:31



  3) test Valid, seeded JWT (DB.SessionTest)
     test/models/session_test.exs:37
     ** (ArgumentError) argument error
     stacktrace:
       (stdlib) :ets.lookup(217132, 1114)
       (postgrex) lib/postgrex/types.ex:294: Postgrex.Types.fetch!/2
       (postgrex) lib/postgrex/types.ex:215: Postgrex.Types.encoder/2
       (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
       (postgrex) lib/postgrex/query.ex:82: DBConnection.Query.Postgrex.Query.encoders/2
       (postgrex) lib/postgrex/query.ex:43: DBConnection.Query.Postgrex.Query.describe/2
       (db_connection) lib/db_connection.ex:884: DBConnection.describe_execute/5
       (db_connection) lib/db_connection.ex:966: anonymous fn/4 in DBConnection.run_meter/5
       (db_connection) lib/db_connection.ex:421: DBConnection.query/4
       (ecto) lib/ecto/adapters/sql.ex:380: Ecto.Adapters.SQL.struct/6
       (ecto) lib/ecto/repo/schema.ex:369: Ecto.Repo.Schema.apply/5
       (ecto) lib/ecto/repo/schema.ex:175: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:570: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:434: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1079: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
       test/models/session_test.exs:45
```

The pattern of code in question that causes these errors is:

```elixir
    {:ok, session = %Session{user_token: _}} = %Session{
      email: Faker.Internet.email,
      type: "User",
      user_token: "DUMMY123"
    }
    |> DB.Repo.insert
```

Dependencies:

```
[john:~/Public/fap/api/api-2.1/apps/db] master(+20/-48)* 1 ± mix deps
* base64url 0.0.1 (Hex package) (rebar)
  locked at 0.0.1 (base64url)
  ok
* connection 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (connection)
  ok
* jose 1.6.1 (Hex package) (mix)
  locked at 1.6.1 (jose)
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy)
  ok
* decimal 1.1.1 (Hex package) (mix)
  locked at 1.1.1 (decimal)
  ok
* poison 1.5.2 (Hex package) (mix)
  locked at 1.5.2 (poison)
  ok
* db_connection 0.2.3 (Hex package) (mix)
  locked at 0.2.3 (db_connection)
  ok
* postgrex 0.11.1 (Hex package) (mix)
  locked at 0.11.1 (postgrex)
  ok
* ecto 2.0.0-beta.0 (https://github.com/elixir-lang/ecto.git) (mix)
  locked at 3bd5087
  ok
* joken 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (joken)
  ok
* geo 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (geo)
  ok
```

**Comment by josevalim** [comment] 2016-02-22 07:35
Does the whole suite fail? Or just the initial tests in the suite? How are you running your migrations?

**Comment by josevalim** [comment] 2016-02-22 07:40
If you can provide a simple app that reproduces the issue btw, it would help a lot, because I cannot reproduce it. :D

**Comment by Gazler** [comment] 2016-02-22 08:54
I have encountered an entire test suite failing with this in ecto 2.0.0 beta. The behaviour also seems random. I'll try to reproduce it in a new app.

For what it is worth, I also have joken as a dependency. Although I have not done any research to determine if this is a coincidence or not.

**Comment by josevalim** [comment] 2016-02-22 09:36
FWIW, these issues must be fixed on Ecto master. If you can't use master, it should also be fixed by removing the two Mix.Task.run calls from your test_helper.exs and adding the following to your mix.exs inside the defp aliases function:

    "test": ["ecto.create --quiet", "ecto.migrate", "test"]

**Closed** 2016-02-22 09:36 UTC

**Comment by JoshSmith** [comment] 2017-11-12 06:26
I've seen this issue come up frequently in our app as of late, both in CI and locally in development. It's [on GitHub](https://github.com/code-corps/code-corps-api) so it's fairly straightforward to pull down, although I can't figure out quite how to reproduce it.

**Comment by fishcakez** [comment] 2017-11-16 02:58
@JoshSmith could you provide the error because the code has changed between this issue and the versions of ecto/postgrex in your lock file.

**Comment by JoshSmith** [comment] 2017-11-16 05:37
@fishcakez I'd actually intended to write an update here but forgot. My issue was caused by a lot of async behavior being run in the background. We took José's advice on mocking and are now running all this async behavior as sync in tests.

**Comment by sheharyarn** [comment] 2018-11-12 22:57
@joshsmith @gazler Were you ever able to figure out the cause or even reproduce this? This randomly happens on our CI (but not on `dev`). When it does happen, it affects anywhere from 60 to 90 tests (out of more than 500+) at random.

Here's what a usual error looks like:

```
  1) test add reaction to thread (MyApp.Web.ReactionResolverTest)
     test/my_app/posts/reaction_resolver_test.exs:56
     ** (ArgumentError) argument error
     stacktrace:
       (stdlib) :ets.lookup(MyApp.GlobalRepo.Pool, #PID<0.140.1>)
       (db_connection) lib/db_connection/ownership/manager.ex:54: DBConnection.Ownership.Manager.lookup/2
       (db_connection) lib/db_connection/ownership.ex:122: DBConnection.Ownership.checkout/2
       (db_connection) lib/db_connection.ex:928: DBConnection.checkout/2
       (db_connection) lib/db_connection.ex:750: DBConnection.run/3
       (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
       (ecto) lib/ecto/repo/schema.ex:125: Ecto.Repo.Schema.insert!/4
       (my_app) test/support/conn_case.ex:96: MyApp.Web.ConnCase.setup_user/2
       (my_app) test/support/conn_case.ex:57: MyApp.Web.ConnCase.__ex_unit_setup_0/1
       (my_app) test/support/conn_case.ex:1: MyApp.Web.ConnCase.__ex_unit__/2
       test/my_app/posts/reaction_resolver_test.exs:1: MyApp.Web.ReactionResolverTest.__ex_unit__/2
```

**Comment by josevalim** [comment] 2018-11-12 23:05
@sheharyarn one possibility is that your application supervision tree is being restarted, causing the repository to be temporarily unavailable. Make sure to enable logging during your tests run and see if there are supervision tree crashes/restarts.

**Comment by sheharyarn** [comment] 2018-11-14 21:51
@josevalim Thank you for your input, it was very helpful in investigating and narrowing down the issue. Just like you said, the problem was stemming from a supervisor that would get killed for some reason and would cause the whole application to go down. The rest of the tests in the suite would immediately fail (I imagine before the tree had a chance to restart).

I have a few questions, I'm hoping you can help me with:

 - What would cause a Supervisor itself to go down (as opposed to only its children) and then further cause the entire application to go down? Shouldn't the supervisor have restarted in case of errors instead of taking its sibling/parent processes down with it?
 - Is the application supervision tree always restarted between tests? Or does it keeping running and restarts as usual when crashes happen?
 - I used `ExUnit.start(trace: true)` and `Process.monitor` to investigate this so far. Do you have any other pointers which could be helpful in tracing supervision tree crashes in the future? Maybe something like `:observer` for the command line?

**Comment by josevalim** [comment] 2018-11-15 09:42
> What would cause a Supervisor itself to go down (as opposed to only its children) and then further cause the entire application to go down? Shouldn't the supervisor have restarted in case of errors instead of taking its sibling/parent processes down with it?

It depends on your supervision strategy and the max restarts and max seconds. If you restart too frequently, then the supervisor will shutdown, causing its parent supervisor to restart it and so on.

> Is the application supervision tree always restarted between tests? Or does it keeping running and restarts as usual when crashes happen?

It keeps running. The app supervision is shared state between tests.

> I used ExUnit.start(trace: true) and Process.monitor to investigate this so far. Do you have any other pointers which could be helpful in tracing supervision tree crashes in the future? Maybe something like :observer for the command line?

You can enable sasl reports. It tells precisely what each supervisor is doing:

    elixir --logger-sasl-reports true -S mix test
